apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cirros-pvc" # Name of the PVC
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-i386-disk.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  #storageClassName: hdd
