apiVersion: v1
kind: Template
metadata:
  name: cirros-demo-template
  annotations:
    description: "OpenShift KubeVirt Cirros VM template"
    tags: "kubevirt,openshift,template,linux"
  labels:
    kubevirt.io/os: fedora28
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    name: ${NAME}
    labels:
      kubevirt-ovm: ovm-${NAME}
  spec:
    running: false
    template:
      metadata:
        labels:
          kubevirt-ovm: ovm-${NAME}
          special: demo-key
      spec:
        domain:
          cpu:
            cores: ${{CPU_CORES}}
          resources:
            requests:
              memory: 1Gi
          devices:
            disks:
            - disk:
                bus: virtio
              name: disk0
              volumeName: root
            - disk:
                bus: virtio
              name: cloudinitdisk
              volumeName: cloudinitvolume
        volumes:
          - name: root
            persistentVolumeClaim:
              claimName: cirros-pvc
          - name: cloudinitvolume
            cloudInitNoCloud:
              userData: |-
                #cloud-config
                password: "redhat"
                chpasswd: { expire: False }
                ssh_authorized_keys:
                - ${KEY}
parameters:
- name: NAME
  description: Name for the new VM
- name: CPU_CORES
  description: Amount of cores
  value: "4"
- description: ssh key
  name: KEY
  value: "add your ssh-public key"